// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateBatchFromImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateBatchFromImage'](arg1, arg2, arg3);
}

export function GenerateBatchFromMultiImages(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateBatchFromMultiImages'](arg1, arg2, arg3);
}

export function GenerateBatchImages(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateBatchImages'](arg1, arg2, arg3);
}

export function GenerateFromImage(arg1, arg2) {
  return window['go']['main']['App']['GenerateFromImage'](arg1, arg2);
}

export function GenerateFromMultiImages(arg1, arg2) {
  return window['go']['main']['App']['GenerateFromMultiImages'](arg1, arg2);
}

export function GenerateImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateImage'](arg1, arg2, arg3);
}

export function GetImageAsDataURL(arg1) {
  return window['go']['main']['App']['GetImageAsDataURL'](arg1);
}

export function GetSavedImages() {
  return window['go']['main']['App']['GetSavedImages']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function OpenImageFile(arg1) {
  return window['go']['main']['App']['OpenImageFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectSaveDirectory() {
  return window['go']['main']['App']['SelectSaveDirectory']();
}
