// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function GenerateBatchFromImage(arg1:string,arg2:string,arg3:number):Promise<main.GenerateResult>;

export function GenerateBatchFromMultiImages(arg1:string,arg2:Array<string>,arg3:number):Promise<main.GenerateResult>;

export function GenerateBatchImages(arg1:string,arg2:string,arg3:number):Promise<main.GenerateResult>;

export function GenerateFromImage(arg1:string,arg2:string):Promise<main.GenerateResult>;

export function GenerateFromMultiImages(arg1:string,arg2:Array<string>):Promise<main.GenerateResult>;

export function GenerateImage(arg1:string,arg2:string,arg3:number):Promise<main.GenerateResult>;

export function GetImageAsDataURL(arg1:string):Promise<string>;

export function GetSavedImages():Promise<Array<string>>;

export function GetSettings():Promise<config.Settings>;

export function OpenImageFile(arg1:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function SelectSaveDirectory():Promise<string>;
